version: "3.5"

services:

   postgresql:
      image: postgis/postgis
      container_name: skynet_db
      ports:
         - 5432:5432
      volumes:
         - ./postgresql/data:/var/lib/postgresql/data
         - ./postgresql/backups:/backups
         - ./postgresql/init:/init
 
      environment:
         ## MAINTENANCE DB
         - POSTGRES_PASSWORD=m2vRgW8euk8DXWDF # TODO work w/ secrets and edit password

   fastapi:
      image: fastapi
      container_name: skynet_api
      build:
         context: ./
         dockerfile: ./fastapi/Dockerfile
      ports: 
         - "80:80"
      volumes:
         - ./fastapi/app:/app
      environment: 
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=m2vRgW8euk8DXWDF
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_DATABASE=skynet

         